global:
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  minikube: true

# This default `make k8s-install-chart` will deploy all of the dependencies: the UI will access an
# PHT backend, which will use the RESTRepository backend to access the ODA REST API, which will connect
# with the PostgreSQL instance.
# The configuration can be changed using the parameters below, or see the `make dev-up` target.

ska-oso-pht-services:
  rest:
    logLevel: debug
    # Use the ska-oso-pht-services default values which is configured to use the remote ska-db-oda deployment.
    # To override this and store in the PHT Services filesystem for example, use the values below
#    oda:
#      backendType: filesystem

ska-db-oda-umbrella:
  ska-db-oda:
    enabled: true
    logLevel: info
    rest:
      enabled: true
      ingress:
        enabled: true
      backend:
        postgres:
          host:
  postgresql:
    enabled: true
  pgadmin4:
    enabled: true
  ska-ser-skuid:
    skuid:
      enabled: true