sonar.projectKey=ska-telescope_oso_ska-oso-pht-ui_6c8fcfc8-da65-44a4-9131-45086cf61c06
sonar.qualitygate.wait=true
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx
sonar.javascript.lcov.reportPaths=build/reports/lcov.info
