
# Configure Ingress
ingress:
  enabled: true
  prependByNamespace: true
  path: pht

runtimeEnv:
  skipPreflightCheck: "true"
  skaOsoServicesUrl: ""
  skaSensitivityCalcUrl: ""
  useLocalData: "false"
  domain: "https://sdhp.stfc.skao.int"
  skaLoginAppUrl: ""
  msentraRedirectUri: ""
  useIndigo: false # Can be overwritten by setting USE_INDIGO environment variable to true
  indigoAuthority: "https://iam-1.staging.devx.skao.int/"
  indigoClientId: "d546e462-637c-44ff-b2b9-3345a960ad42"
  indigoRedirectUri: "/"
  indigoScope: "pht:readwrite pht:read openid profile"
  indigoAudience: "test:pht"

component: pht-ui
function: ui
domain: operations
enabled: true
image:
  registry: artefact.skao.int
  image: ska-oso-pht-ui
  tag: ~
  pullPolicy: IfNotPresent

vault:
  enabled: true
  mount: dev
  secretPath: "stargazers/ska-oso-pht-ui"
  secretKeys:
  - "MSENTRA_CLIENT_ID"
  - "MSENTRA_TENANT_ID"
