ingress:
  enabled: true
  production: false
  host: ""
  path: pht
  prependByNamespace: true # if true, the ingress rule will use `/{NAMESPACE}/{.Values.ingress.path}`

runtimeEnv:
  skaOsoServicesUrl: ~ # Set dynamically in the Makefile
  skaSensitivityCalcUrl: ""
  useLocalData: "false"
  msentraRedirectUri: ""
  msenstraClientId: "2445e300-54c9-470f-9578-0f54840672af"
  msenstraTenantId: "78887040-bad7-494b-8760-88dcacfb3805"
  useIndigo: false # Can be overwritten by setting USE_INDIGO environment variable to true
  indigoAuthority: "https://iam-1.staging.devx.skao.int/"
  indigoClientId: "d546e462-637c-44ff-b2b9-3345a960ad42"
  indigoScope: "pht:readwrite pht:read openid profile"
  indigoAudience: "test:pht"

component: pht-ui
function: ui
domain: operations
enabled: true
image:
  registry: artefact.skao.int
  image: ska-oso-pht-ui
  tag: ~
  pullPolicy: IfNotPresent
