import { ReviewDashboardBackend } from '@/utils/types/reviewDashboard';

export const mockReviewDashboard: ReviewDashboardBackend[] = [
  {
    prsl_id: 'prp-ska01-202204-01',
    title: 'The Milky Way View',
    science_category: 'Science Category',
    proposal_status: 'submitted',
    proposal_type: 'standard_proposal',
    cycle: 'SKA_5000_2023',
    proposal_attributes: [],
    array: 'LOW',
    panel_id: 'panel-t0001-2025-07-28-00001-5576209',
    panel_name: 'New Panel',
    reviewer_id: 'c8f8f18a-3c70-4c39-8ed9-2d8d180d99b1',
    reviewer_status: 'Pending',
    review_status: undefined,
    conflict: false,
    review_id: undefined,
    review_rank: undefined,
    comments: undefined,
    decision_id: undefined,
    assigned_proposal: 'Yes',
    recommendation: undefined,
    decision_status: undefined,
    panel_rank: undefined,
    panel_score: undefined,
    review_submitted_on: undefined,
    decision_on: undefined
  },
  {
    prsl_id: 'prp-ska01-202204-02',
    title: 'The Milky Way View',
    science_category: 'Science Category',
    proposal_status: 'submitted',
    proposal_type: 'standard_proposal',
    cycle: 'SKA_5000_2023',
    proposal_attributes: [],
    array: 'LOW',
    panel_id: 'panel-t0001-2025-07-28-00001-5576209',
    panel_name: 'New Panel',
    reviewer_id: 'c8f8f18a-3c70-4c39-8ed9-2d8d180d99b1',
    reviewer_status: 'Pending',
    review_status: undefined,
    conflict: false,
    review_id: undefined,
    review_rank: undefined,
    comments: undefined,
    decision_id: undefined,
    assigned_proposal: 'Yes',
    recommendation: undefined,
    decision_status: undefined,
    panel_rank: undefined,
    panel_score: undefined,
    review_submitted_on: undefined,
    decision_on: undefined
  },
  {
    prsl_id: 'prp-ska01-202204-03',
    title: 'The Milky Way View',
    science_category: 'Science Category',
    proposal_status: 'submitted',
    proposal_type: 'standard_proposal',
    cycle: 'SKA_5000_2023',
    proposal_attributes: [],
    array: 'LOW',
    panel_id: 'panel-t0001-2025-07-28-00001-5576209',
    panel_name: 'New Panel',
    reviewer_id: 'c8f8f18a-3c70-4c39-8ed9-2d8d180d99b1',
    reviewer_status: 'Pending',
    review_status: undefined,
    conflict: false,
    review_id: undefined,
    review_rank: undefined,
    comments: undefined,
    decision_id: undefined,
    assigned_proposal: 'No',
    recommendation: undefined,
    decision_status: undefined,
    panel_rank: undefined,
    panel_score: undefined,
    review_submitted_on: undefined,
    decision_on: undefined
  }
];
