import { MockProposalFrontend } from '@/services/axios/put/putProposal/mockProposalFrontend';

// Define a mock store object with all required properties and methods
const completeMockStore = {
  application: {
    content1: [0, 0, 0],
    content2: MockProposalFrontend,
    content3: {},
    content4: {}
  },
  updateAppContent1: vi.fn(),
  updateAppContent2: vi.fn(),
  helpComponent: vi.fn(),
  user: null,
  telescopeAccess: vi.fn(),
  isDeveloper: false,
  clearUser: vi.fn(() => ({ payload: undefined, type: 'user/clear' })),
  updateUser: vi.fn(),
  updateAppContent3: vi.fn(),
  updateAppContent4: vi.fn(),
  updateAppContent5: vi.fn(),
  updateAppContent6: vi.fn(),
  updateAppContent7: vi.fn(),
  updateAppContent8: vi.fn(),
  updateAppContent9: vi.fn(),
  updateAppContent10: vi.fn(),
  updateAppContent11: vi.fn(),
  updateAppContent12: vi.fn(),
  updateAppContent13: vi.fn(),
  updateAppContent14: vi.fn(),
  updateAppContent15: vi.fn(),
  updateAppContent16: vi.fn(),
  updateAppContent17: vi.fn(),
  updateAppContent18: vi.fn(),
  updateAppContent19: vi.fn(),
  updateAppContent20: vi.fn(),
  updateAppContent21: vi.fn(),
  updateAppContent22: vi.fn(),
  updateAppContent23: vi.fn(),
  updateAppContent24: vi.fn(),
  updateAppContent25: vi.fn(),
  setAccessibility: vi.fn(),
  access: {},
  clearAccess: vi.fn(),
  updateAccess: vi.fn(),
  clearApp: vi.fn(),
  updateApp: vi.fn(),
  clearHelp: vi.fn(),
  updateHelp: vi.fn(),
  clearTelescope: vi.fn(),
  updateTelescope: vi.fn(),
  clearDeveloper: vi.fn(),
  updateDeveloper: vi.fn(),
  clearAccessibility: vi.fn(),
  updateAccessibility: vi.fn(),
  help: '',
  helpContent: '',
  helpToggle: false,
  helpComponentURL: '',
  helpComponentId: '',
  notify: vi.fn(),
  notifyClear: vi.fn(),
  notifyError: vi.fn(),
  notifySuccess: vi.fn()
  // Add any additional properties required by the useStore type here
};

export default completeMockStore;
