export type ReviewDashboardBackend = {
  prsl_id: string;
  title: string;
  science_category?: string;
  proposal_status: string;
  proposal_type: string;
  cycle: string;
  proposal_attributes: string[];
  array: string;
  panel_id?: string;
  panel_name?: string;
  reviewer_id?: string;
  reviewer_status?: string;
  review_status?: string;
  conflict: boolean;
  review_id?: string;
  review_rank?: number;
  comments?: string;
  decision_id?: string;
  assigned_proposal?: string;
  recommendation?: string;
  decision_status?: string;
  panel_rank?: number;
  panel_score?: number;
  review_submitted_on?: string;
  decision_on?: string;
  location?: string;
};

export type ReviewDashboard = {
  prslId: string;
  title: string;
  scienceCategory?: string;
  proposalStatus: string;
  proposalType: string;
  cycle: string;
  proposalAttributes: string[];
  array: string;
  panelId?: string;
  panelName?: string;
  reviewerId?: string;
  reviewerStatus?: string;
  reviewStatus?: string;
  conflict: boolean;
  reviewId?: string;
  reviewRank?: number;
  comments?: string;
  decisionId?: string;
  assignedProposal?: string;
  recommendation?: string;
  decisionStatus?: string;
  panelRank?: number;
  panelScore?: number;
  reviewSubmittedOn?: string;
  decisionOn?: string;
  location?: string;
};
