import { Entity, mintSkuid } from '@ska-telescope/skuid';
import { helpers } from '@utils/helpers.ts';
import {
  OSO_SERVICES_PROPOSAL_PATH,
  SKA_OSO_SERVICES_URL,
  TEAM_STATUS_TYPE_OPTIONS,
  USE_LOCAL_DATA
} from '@utils/constants.ts';
import Proposal from '@utils/types/proposal.tsx';
import useAxiosAuthClient, { refreshAuthToken } from '../../axiosAuthClient/axiosAuthClient';
import { mapping } from '../../get/getProposal/getProposal.tsx';
import MappingPutProposal from '../../put/putProposal/putProposalMapping.tsx';
import { MockProposalBackend } from './mockProposalBackend.tsx';

export function mockPostProposal() {
  return mapping(MockProposalBackend);
}

async function PostProposal(
  authAxiosClient: ReturnType<typeof useAxiosAuthClient>,
  proposal: Proposal,
  status?: string
): Promise<Proposal | { error: string }> {
  if (USE_LOCAL_DATA) {
    return mockPostProposal();
  }

  try {
    const URL_PATH = `${OSO_SERVICES_PROPOSAL_PATH}/create`;
    // Use the full mapping so cloned proposals carry all content (targets, observations, etc.).
    // Note: The new prsl_id is now minted here. As a fallback if this fails the entity
    // will be passed in without an ID  (see ska-db-oda's get_identifier_or_fetch_from_skuid) and be
    // generated by the service - hence mapping the returned rather than assuming it will be the same.
    // investigator_refs is omitted — the backend builds it from the investigators in proposal_info.
    // investigator status is reset to 'Pending' — invitation to the new proposal is fresh.
    // result_details is reset to [] — sensitivity-calc results are stale for a new proposal.
    const {
      prsl_id: _omit,
      investigator_refs: _invRefs,
      ...mapped
    } = MappingPutProposal(proposal, status as string);
    const convertedProposal = helpers.transform.trimObject({
      ...mapped,
      prsl_id: mintSkuid(Entity.PRP),
      proposal_info: {
        ...mapped.proposal_info,
        investigators:
          mapped.proposal_info.investigators?.map(({ status: _s, ...inv }) => ({
            ...inv,
            status: TEAM_STATUS_TYPE_OPTIONS.pending
          })) ?? []
      },
      observation_info: {
        ...mapped.observation_info,
        result_details: []
      }
    });

    const result = await authAxiosClient.post(
      `${SKA_OSO_SERVICES_URL}${URL_PATH}`,
      convertedProposal
    );
    if (!result || !result?.data) {
      return { error: 'error.API_UNKNOWN_ERROR' };
    }
    // The backend just granted this user admin group membership on the new proposal
    // (create_membership) - refresh so the next request's token actually reflects it.
    await refreshAuthToken();
    return mapping(result.data);
  } catch (e) {
    if (e instanceof Error) {
      return { error: e.message };
    }
    return { error: 'error.API_UNKNOWN_ERROR' };
  }
}

export default PostProposal;
