{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.production }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
{{ include "ska-oso-pht-ui.labels" . | indent 4 }}
  name: {{ $.Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ default "" .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Chart.Name }}-service
            port:
              number: 80
        path: {{ include "ska-oso-pht-ui.ingress.path" . }}
        pathType: ImplementationSpecific
{{- else }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
{{ include "ska-oso-pht-ui.labels" . | indent 4 }}
  name: {{ $.Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ $.Chart.Name }}-service
            port:
              number: 80
        # Match everything but '/oso' which is reserved for back-end
        path: {{ include "ska-oso-pht-ui.ingress.path" . }}/(?!oso)(.*)
        pathType: ImplementationSpecific
{{- end }}
{{- end }}