{{- if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{ include "ska-oso-darkMode-ui.labels" . | indent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
{{ include "ska-oso-darkMode-ui.labels" . | indent 4 }}
  name: {{ $.Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ $.Chart.Name }}-service
            port:
              number: 80
        # Match everything but '/api' which is reserved for back-end
        path: {{ include "ska-oso-darkMode-ui.ingress.path" . }}/(?!api)(.*)
        pathType: ImplementationSpecific

{{- end }}
