{{- if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ska-oso-pht-ui.name" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
{{ include "ska-oso-pht-ui.labels" . | indent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Release.Namespace }}/pht/ui/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "ska-oso-pht-ui.name" . }}
                port:
                  number: 80
{{- end }}
